repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 1ba6bfc
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8