repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: src/PreTrainedFasterGradCAMDemo.egg-info/
      - id: end-of-file-fixer
        exclude: src/PreTrainedFasterGradCAMDemo.egg-info/
      - id: requirements-txt-fixer
      - id: check-yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [.]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 1ba6bfc
    hooks:
      - id: isort
        args: [.]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [.]
